/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: badges
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-04-22
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

const badgesSchema = new Schema({
    "badgeKey": Number,
    "badgeTitle": String,
    "imageUrl": String,
    "badgeDesc": String,
}, { collection: "badges" })

export default mongoose.models.badges || model('badges', badgesSchema)