/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: questions
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-04-22
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const questions_Mongoose = new Schema({
    "quizKey": Number,
    "questionKey": Number,
    "question": String,
    "optionA": String,
    "optionB": String,
    "optionC": String,
    "optionD": String,
    "answer": String,
}, { collection: "questions" })

export default mongoose.models.questions_Mongoose || model("questions_Mongoose", questions_Mongoose);