/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: quiz
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-04-22
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const quiz_Mongoose = new Schema({
    "quizKey": Number,
    "title": Number,
    "quizDesc": String,
    "timelimit": Number,
    "questionAmount": Number,
    "marks": Number,
    "imagePath": String,
    "difficulty": Number,
}, { collection: "quiz" })

export default mongoose.models.quiz_Mongoose || model("quiz_Mongoose", quiz_Mongoose);