/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: resumeTemplate
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-04-22
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const resumeTemplate_Mongoose = new Schema({
    "title": String,
    "templateDesc": String,
    "filename": String,
    "imagePath": String,
}, { collection: "resumeTemplate" })

export default mongoose.models.resumeTemplate_Mongoose || model("resumeTemplate_Mongoose", resumeTemplate_Mongoose);