/**
* Generated by MongoDB Relational Migrator
* https://www.mongodb.com/products/relational-migrator
* Collection: solvedQuizzes
* Language: JavaScript
* Template: Mongoose
* Generated on 2025-04-22
*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const solvedQuizzes_Mongoose = new Schema({
    "userkey": Number,
    "quizKey": Number,
    "score": Number,
    "dateOfSol": String,
    "wrongAnswerList": Object,
    "correctAnswerList": Object,
}, { collection: "solvedQuizzes" })

export default mongoose.models.solvedQuizzes_Mongoose || model("solvedQuizzes_Mongoose", solvedQuizzes_Mongoose);